### PR TITLE
No success messasge when github login is failed

### LINKED ISSUE #91: Throwing error when trying to log into the course
## Description
When attempting to log into the openmined course i was thrown the following error.

## How to Reproduce
1. Go to the https://courses.openmined.org/signin
2. Click on Sign in with Github
3. Enter Github credential

## Expected Behavior
Should have signed me into the course

## Screenshots
image

## System Information
 - OS: Windows 10
 - Browser: Google Chrome

## Additional Context
I have tried on multiple browsers but still the same error unfortunately

### PR DESCRIPTION
**Pull request by ITsolution-git**
## Description
Sign in using email/password.
Sign out
Signin using github with same email
You get success/error message at the same time.

The success message should be removed.

## Affected Dependencies
None

## How has this been tested?
None

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

File: apps/courses/src/components/forms/users/SignIn.tsx [hunk 1]
```diff
@@ -61,11 +61,10 @@ export default ({ callback, ...props }: SignInFormProps) => {
   const onGithubSubmit = async () => {
     analytics.logEvent('Login', { method: 'github' });
 
-    const authUser = await auth
+    await auth
```
Comment (tcp) [inline apps/courses/src/components/forms/users/SignIn.tsx]: `onGithubSubmit` uses async/await but `onSubmit` above does not. What do you think about using the same for these functions?

**Review by tcp — CHANGES_REQUESTED** [review]
Danny, please check `onSubmit` and `onGithubSubmit` :)

**Review by tcp — APPROVED** [review]
